from patch import Patch
def levelsPatch(selectedLevel):
   if selectedLevel==1:
        
      patchLevel1 = Patch(5,9)
   
      patchLevel1.set_wall(0,0)
      patchLevel1.set_wall(0,1)
      patchLevel1.set_wall(0,2)
      patchLevel1.set_wall(0,3)
      patchLevel1.set_wall(0,4)
      patchLevel1.set_wall(0,5)
      patchLevel1.set_wall(1,0)
      # patchLevel1.set_wall(1,5)
      patchLevel1.set_wall(1,6)
      patchLevel1.set_wall(2,0)
      # patchLevel1.set_wall(2,6)
      patchLevel1.set_wall(2,7)
      patchLevel1.set_wall(2,8)
      patchLevel1.set_wall(3,0)
      
      patchLevel1.set_wall(3,8)
      patchLevel1.set_wall(4,0)
      patchLevel1.set_wall(4,1)
      patchLevel1.set_wall(4,2)
      patchLevel1.set_wall(4,3)
      patchLevel1.set_wall(4,4)
      patchLevel1.set_wall(4,5)
      patchLevel1.set_wall(4,6)
      patchLevel1.set_wall(4,7)
      patchLevel1.set_wall(4,8)
      patchLevel1.set_goal(1,1,"R")
      patchLevel1.set_goal(2,5,"B")
      patchLevel1.set_moving_cell(3,6,"b")
      patchLevel1.set_moving_cell(3,5,"r")
      return patchLevel1
   elif selectedLevel==2:
      patchLevel2 = Patch(11,7)
   
      patchLevel2.set_wall(0,0)
      patchLevel2.set_wall(0,1)
      patchLevel2.set_wall(0,2)
      patchLevel2.set_wall(0,3)
      patchLevel2.set_wall(0,4)
      patchLevel2.set_wall(0,5)
      patchLevel2.set_wall(0,6)
      patchLevel2.set_wall(1,0)
      patchLevel2.set_wall(1,6)
      patchLevel2.set_wall(2,0)
      patchLevel2.set_wall(2,4)
      patchLevel2.set_wall(2,6)
      patchLevel2.set_wall(3,0)
      patchLevel2.set_wall(3,4)
      patchLevel2.set_wall(3,6)
      patchLevel2.set_wall(4,0)
      patchLevel2.set_wall(4,4)
      patchLevel2.set_wall(4,6)
      patchLevel2.set_wall(5,0)
      patchLevel2.set_wall(5,3)
      patchLevel2.set_wall(5,4)
      patchLevel2.set_wall(5,6)
      patchLevel2.set_wall(6,0)
      patchLevel2.set_wall(6,6)
      patchLevel2.set_wall(7,0)
      patchLevel2.set_wall(7,5)    
      patchLevel2.set_wall(7,6)    
      patchLevel2.set_wall(8,0)    
      patchLevel2.set_wall(8,1)    
      patchLevel2.set_wall(8,2)    
      patchLevel2.set_wall(8,3)    
      patchLevel2.set_wall(8,6)    
      patchLevel2.set_wall(9,1)    
      patchLevel2.set_wall(9,6)    
      patchLevel2.set_wall(10,1)    
      patchLevel2.set_wall(10,2)    
      patchLevel2.set_wall(10,3)    
      patchLevel2.set_wall(10,4)    
      patchLevel2.set_wall(10,5)    
      patchLevel2.set_wall(10,6)    
      patchLevel2.set_moving_cell(3,1,"r")
      patchLevel2.set_moving_cell(2,3,"b")

      patchLevel2.set_goal(4,3,"R")
      patchLevel2.set_goal(1,5,"B")
      return patchLevel2
   elif selectedLevel==3:
      patchLevel3 = Patch(5,8)
   
      patchLevel3.set_wall(0,1)
      patchLevel3.set_wall(0,2)
      patchLevel3.set_wall(0,3)
      patchLevel3.set_wall(1,0)
      patchLevel3.set_wall(1,1)
      patchLevel3.set_wall(1,3)
      patchLevel3.set_wall(1,4)
      patchLevel3.set_wall(1,5)
      patchLevel3.set_wall(1,6)
      patchLevel3.set_wall(1,7)
      patchLevel3.set_wall(2,0)
      patchLevel3.set_wall(2,7)
      patchLevel3.set_wall(3,0)
      patchLevel3.set_wall(3,2)
      patchLevel3.set_wall(3,4)
      patchLevel3.set_wall(3,5)
      patchLevel3.set_wall(3,6)
      patchLevel3.set_wall(3,7)
      patchLevel3.set_wall(4,0)
      patchLevel3.set_wall(4,1)
      patchLevel3.set_wall(4,2)
      patchLevel3.set_wall(4,3)
      patchLevel3.set_wall(4,4)
      patchLevel3.set_goal(3,3,"R")
      patchLevel3.set_goal(3,1,"B")
      patchLevel3.set_goal(1,2,"Y")
      patchLevel3.set_moving_cell(2,2,"r")
      patchLevel3.set_moving_cell(2,3,"b")
      patchLevel3.set_moving_cell(2,1,"y")
      return patchLevel3
   elif selectedLevel==4:
      patchLevel4 = Patch(5,5)
   
      patchLevel4.set_wall(0,0)
      patchLevel4.set_wall(0,1)
      patchLevel4.set_wall(0,2)
      patchLevel4.set_wall(0,3)
      patchLevel4.set_wall(0,4)
      # patchLevel4.set_wall(0,5)
      patchLevel4.set_wall(1,0)
      patchLevel4.set_wall(1,4)
      # patchLevel4.set_wall(1,5)
      patchLevel4.set_wall(2,0)
      # patchLevel4.set_wall(2,6)
      patchLevel4.set_wall(2,4)
      patchLevel4.set_wall(3,0)
      patchLevel4.set_wall(3,4)
      patchLevel4.set_wall(4,0)
      
      patchLevel4.set_wall(4,4)

      patchLevel4.set_wall(4,1)
      patchLevel4.set_wall(4,4)
      patchLevel4.set_wall(4,2)
      patchLevel4.set_wall(4,3)
      # patchLevel4.set_wall(3,5)
      patchLevel4.set_wall(2,2)

      patchLevel4.set_goal(1,1,"B")
      patchLevel4.set_goal(3,3,"R")
      
      patchLevel4.set_moving_cell(3,2,"b")
      patchLevel4.set_moving_cell(1,2,"r")
      return patchLevel4 
   elif selectedLevel==5:
      patchLevel5 = Patch(5,5)
   
      patchLevel5.set_wall(0,1)
      patchLevel5.set_wall(0,2)
      patchLevel5.set_wall(0,3)
      patchLevel5.set_wall(0,4)
      patchLevel5.set_wall(0,0)
      patchLevel5.set_wall(1,0)
      # patchLevel5.set_wall(1,5)
      patchLevel5.set_wall(1,4)
      patchLevel5.set_wall(2,0)
      # patchLevel5.set_wall(2,6)
      patchLevel5.set_wall(2,4)
      # patchLevel5.set_wall(2,8)
      # patchLevel5.set_wall(0,0)
      patchLevel5.set_wall(3,0)
      
      patchLevel5.set_wall(3,4)
      patchLevel5.set_wall(4,0)
      patchLevel5.set_wall(4,1)
      patchLevel5.set_wall(4,2)
      patchLevel5.set_wall(4,3)
      patchLevel5.set_wall(4,4)
      # patchLevel5.set_wall(4,5)
      # patchLevel5.set_wall(4,6)
      # patchLevel5.set_wall(4,7)
      # patchLevel5.set_wall(4,8)
      patchLevel5.set_goal(1,3,"R")
      # patchLevel5.set_goal(1,5,3)
      
      patchLevel5.set_moving_cell(3,1,"r")
      # patchLevel5.set_moving_cell(3,5,6)
      return patchLevel5
   elif selectedLevel==20:
      patchLevel6 = Patch(5,9)
   
      patchLevel6.set_wall(0,3)
      patchLevel6.set_wall(0,4)
      patchLevel6.set_wall(0,5)
      patchLevel6.set_wall(0,6)

      patchLevel6.set_wall(1,0)
      # patchLevel6.set_wall(1,5)
      patchLevel6.set_wall(1,1)
      patchLevel6.set_wall(1,2)
      patchLevel6.set_wall(1,3)
      patchLevel6.set_wall(1,6)
      patchLevel6.set_wall(1,7)
      patchLevel6.set_wall(1,8)
      patchLevel6.set_wall(2,0)
      patchLevel6.set_wall(2,8)

      patchLevel6.set_wall(3,0)
      
      patchLevel6.set_wall(3,8)
      patchLevel6.set_wall(3,6)
      patchLevel6.set_wall(3,3)
      patchLevel6.set_wall(4,0)
      patchLevel6.set_wall(4,1)
      patchLevel6.set_wall(4,2)
      patchLevel6.set_wall(4,3)
      patchLevel6.set_wall(4,4)
      patchLevel6.set_wall(4,5)
      patchLevel6.set_wall(4,6)
      patchLevel6.set_wall(4,7)
      patchLevel6.set_wall(4,8)
      patchLevel6.set_goal(1,5,"Y")
      patchLevel6.set_goal(2,1,"B")
      patchLevel6.set_goal(3,2,"P")
      patchLevel6.set_goal(3,4,"R")
      patchLevel6.set_goal(3,7,"G")
      patchLevel6.set_moving_cell(1,4,"r")
      patchLevel6.set_moving_cell(2,3,"b")
      patchLevel6.set_moving_cell(2,2,"p")
      patchLevel6.set_moving_cell(3,2,"g")
      patchLevel6.set_moving_cell(3,7,"y")
 
      return patchLevel6
   elif selectedLevel==10:
      patchLevel6 = Patch(8,12)
   
      patchLevel6.set_wall(0,2)
      patchLevel6.set_wall(0,3)
      patchLevel6.set_wall(0,4)
      patchLevel6.set_wall(0,5)
      patchLevel6.set_wall(0,6)
      patchLevel6.set_wall(0,7)
      patchLevel6.set_wall(0,8)
      patchLevel6.set_wall(0,9)
      patchLevel6.set_wall(1,1)
      patchLevel6.set_wall(1,2)
      patchLevel6.set_wall(1,9)
      patchLevel6.set_wall(1,10)
      patchLevel6.set_wall(2,0)
      patchLevel6.set_wall(2,4)
      patchLevel6.set_wall(2,7)
      patchLevel6.set_wall(2,1)
      patchLevel6.set_wall(2,10)
      patchLevel6.set_wall(2,11)
      patchLevel6.set_wall(3,0)
      patchLevel6.set_wall(3,3)
      patchLevel6.set_wall(3,8)
      patchLevel6.set_wall(3,11)
      patchLevel6.set_wall(4,0)
      patchLevel6.set_wall(4,5)
      patchLevel6.set_wall(4,8)
      patchLevel6.set_wall(4,9)
      patchLevel6.set_wall(4,11)
      patchLevel6.set_wall(5,0)
      patchLevel6.set_wall(5,2)
      patchLevel6.set_wall(5,4)
      patchLevel6.set_wall(5,5)
      patchLevel6.set_wall(5,9)
      patchLevel6.set_wall(5,11)
      patchLevel6.set_wall(6,0)
      patchLevel6.set_wall(6,4)
      patchLevel6.set_wall(6,11)
      patchLevel6.set_wall(7,0)
      patchLevel6.set_wall(7,1)
      patchLevel6.set_wall(7,2)
      patchLevel6.set_wall(7,3)
      patchLevel6.set_wall(7,4)
      patchLevel6.set_wall(7,5)
      patchLevel6.set_wall(7,6)
      patchLevel6.set_wall(7,7)
      patchLevel6.set_wall(7,8)
      patchLevel6.set_wall(7,9)
      patchLevel6.set_wall(7,10)
      patchLevel6.set_wall(7,11)
      patchLevel6.set_goal(3,5,"R")
      patchLevel6.set_goal(2,6,"B")
      patchLevel6.set_moving_cell(5,1,"r")
      patchLevel6.set_moving_cell(5,10,"b")
      return patchLevel6
   elif selectedLevel==30:
      patchLevel6 = Patch(6,16)
   
      patchLevel6.set_wall(0,3)
      patchLevel6.set_wall(0,4)
      patchLevel6.set_wall(0,5)
      patchLevel6.set_wall(0,6)
      patchLevel6.set_wall(0,7)
      patchLevel6.set_wall(0,8)
      patchLevel6.set_wall(0,10)
      patchLevel6.set_wall(0,11)
      patchLevel6.set_wall(0,12)
      patchLevel6.set_wall(0,13)
      patchLevel6.set_wall(0,14)
      patchLevel6.set_wall(0,15)
      patchLevel6.set_wall(1,0)
      patchLevel6.set_wall(1,1)
      patchLevel6.set_wall(1,2)
      patchLevel6.set_wall(1,3)
      patchLevel6.set_wall(1,4)
      patchLevel6.set_wall(1,8)
      patchLevel6.set_wall(1,9)
      patchLevel6.set_wall(1,10)
      patchLevel6.set_wall(1,12)
      patchLevel6.set_wall(1,13)
      patchLevel6.set_wall(1,15)
      patchLevel6.set_wall(2,0)
      patchLevel6.set_wall(2,6)
      patchLevel6.set_wall(2,15)
      patchLevel6.set_wall(3,12)
      patchLevel6.set_wall(3,0)
      patchLevel6.set_wall(3,15)
      patchLevel6.set_wall(4,0)
      patchLevel6.set_wall(4,1)
      patchLevel6.set_wall(4,2)
      patchLevel6.set_wall(4,3)
      patchLevel6.set_wall(4,4)
      patchLevel6.set_wall(4,6)
      patchLevel6.set_wall(4,7)
      patchLevel6.set_wall(4,9)
      patchLevel6.set_wall(4,10)
      patchLevel6.set_wall(4,11)
      patchLevel6.set_wall(4,12)
      patchLevel6.set_wall(4,13)
      patchLevel6.set_wall(4,14)
      patchLevel6.set_wall(4,15)
      patchLevel6.set_wall(5,4)
      patchLevel6.set_wall(5,5)
      patchLevel6.set_wall(5,6)
      patchLevel6.set_wall(5,7)
      patchLevel6.set_wall(5,9)
      patchLevel6.set_slim_wall(5,8)
      # patchLevel6.set_slim_wall(4,5)

      patchLevel6.set_white_goal(3,11)
 
      patchLevel6.set_moving_cell(3,1,"y")
      patchLevel6.set_moving_cell(2,2,"b")
      patchLevel6.set_moving_cell(3,2,"p")
      patchLevel6.set_moving_cell(2,1,"r")
      patchLevel6.set_moving_cell(2,3,"g")
      patchLevel6.set_goal(4,8,"B")
      patchLevel6.set_goal(1,7,"P")
      patchLevel6.set_goal(1,14,"G")
      patchLevel6.set_goal(1,11,"Y")
 
      return patchLevel6
   else:
      print('wronge input, select from 1 ... 8')