from patch import Patch
def levelsPatch(selectedLevel):
   if selectedLevel==1:
        
      patchLevel1 = Patch(5,9)
   
      patchLevel1.set_wall(0,0)
      patchLevel1.set_wall(0,1)
      patchLevel1.set_wall(0,2)
      patchLevel1.set_wall(0,3)
      patchLevel1.set_wall(0,4)
      patchLevel1.set_wall(0,5)
      patchLevel1.set_wall(1,0)
      # patchLevel1.set_wall(1,5)
      patchLevel1.set_wall(1,6)
      patchLevel1.set_wall(2,0)
      # patchLevel1.set_wall(2,6)
      patchLevel1.set_wall(2,7)
      patchLevel1.set_wall(2,8)
      patchLevel1.set_wall(3,0)
      
      patchLevel1.set_wall(3,8)
      patchLevel1.set_wall(4,0)
      patchLevel1.set_wall(4,1)
      patchLevel1.set_wall(4,2)
      patchLevel1.set_wall(4,3)
      patchLevel1.set_wall(4,4)
      patchLevel1.set_wall(4,5)
      patchLevel1.set_wall(4,6)
      patchLevel1.set_wall(4,7)
      patchLevel1.set_wall(4,8)
      patchLevel1.set_goal(1,1,"R")
      patchLevel1.set_goal(2,5,"B")
      patchLevel1.set_moving_cell(3,6,"b")
      patchLevel1.set_moving_cell(3,5,"r")
      return patchLevel1
   elif selectedLevel==2:
      patchLevel2 = Patch(11,7)
   
      patchLevel2.set_wall(0,0)
      patchLevel2.set_wall(0,1)
      patchLevel2.set_wall(0,2)
      patchLevel2.set_wall(0,3)
      patchLevel2.set_wall(0,4)
      patchLevel2.set_wall(0,5)
      patchLevel2.set_wall(0,6)
      patchLevel2.set_wall(1,0)
      patchLevel2.set_wall(1,6)
      patchLevel2.set_wall(2,0)
      patchLevel2.set_wall(2,4)
      patchLevel2.set_wall(2,6)
      patchLevel2.set_wall(3,0)
      patchLevel2.set_wall(3,4)
      patchLevel2.set_wall(3,6)
      patchLevel2.set_wall(4,0)
      patchLevel2.set_wall(4,4)
      patchLevel2.set_wall(4,6)
      patchLevel2.set_wall(5,0)
      patchLevel2.set_wall(5,3)
      patchLevel2.set_wall(5,4)
      patchLevel2.set_wall(5,6)
      patchLevel2.set_wall(6,0)
      patchLevel2.set_wall(6,6)
      patchLevel2.set_wall(7,0)
      patchLevel2.set_wall(7,5)    
      patchLevel2.set_wall(7,6)    
      patchLevel2.set_wall(8,0)    
      patchLevel2.set_wall(8,1)    
      patchLevel2.set_wall(8,2)    
      patchLevel2.set_wall(8,3)    
      patchLevel2.set_wall(8,6)    
      patchLevel2.set_wall(9,1)    
      patchLevel2.set_wall(9,6)    
      patchLevel2.set_wall(10,1)    
      patchLevel2.set_wall(10,2)    
      patchLevel2.set_wall(10,3)    
      patchLevel2.set_wall(10,4)    
      patchLevel2.set_wall(10,5)    
      patchLevel2.set_wall(10,6)    
      patchLevel2.set_moving_cell(3,1,"r")
      patchLevel2.set_moving_cell(2,3,"b")

      patchLevel2.set_goal(4,3,"R")
      patchLevel2.set_goal(1,5,"B")
      return patchLevel2
   elif selectedLevel==3:
      patchLevel3 = Patch(5,8)
   
      patchLevel3.set_wall(0,1)
      patchLevel3.set_wall(0,2)
      patchLevel3.set_wall(0,3)
      patchLevel3.set_wall(1,0)
      patchLevel3.set_wall(1,1)
      patchLevel3.set_wall(1,3)
      patchLevel3.set_wall(1,4)
      patchLevel3.set_wall(1,5)
      patchLevel3.set_wall(1,6)
      patchLevel3.set_wall(1,7)
      patchLevel3.set_wall(2,0)
      patchLevel3.set_wall(2,7)
      patchLevel3.set_wall(3,0)
      patchLevel3.set_wall(3,2)
      patchLevel3.set_wall(3,4)
      patchLevel3.set_wall(3,5)
      patchLevel3.set_wall(3,6)
      patchLevel3.set_wall(3,7)
      patchLevel3.set_wall(4,0)
      patchLevel3.set_wall(4,1)
      patchLevel3.set_wall(4,2)
      patchLevel3.set_wall(4,3)
      patchLevel3.set_wall(4,4)
      patchLevel3.set_goal(3,3,"R")
      patchLevel3.set_goal(3,1,"B")
      patchLevel3.set_goal(1,2,"Y")
      patchLevel3.set_moving_cell(2,2,"r")
      patchLevel3.set_moving_cell(2,3,"b")
      patchLevel3.set_moving_cell(2,1,"y")
      return patchLevel3
   elif selectedLevel==4:
      patchLevel4 = Patch(5,9)
   
      patchLevel4.set_wall(0,1)
      patchLevel4.set_wall(0,2)
      patchLevel4.set_wall(0,3)
      patchLevel4.set_wall(0,4)
      patchLevel4.set_wall(0,5)
      patchLevel4.set_wall(1,0)
      # patchLevel4.set_wall(1,5)
      patchLevel4.set_wall(1,6)
      patchLevel4.set_wall(2,0)
      # patchLevel4.set_wall(2,6)
      patchLevel4.set_wall(2,7)
      patchLevel4.set_wall(2,8)
      patchLevel4.set_wall(0,0)
      patchLevel4.set_wall(3,0)
      
      patchLevel4.set_wall(3,8)
      patchLevel4.set_wall(4,0)
      patchLevel4.set_wall(4,1)
      patchLevel4.set_wall(4,2)
      patchLevel4.set_wall(4,3)
      patchLevel4.set_wall(4,4)
      patchLevel4.set_wall(4,5)
      patchLevel4.set_wall(4,6)
      patchLevel4.set_wall(4,7)
      patchLevel4.set_wall(4,8)
      patchLevel4.set_goal(1,1,2)
      patchLevel4.set_goal(1,5,3)
      
      patchLevel4.set_moving_cell(3,6,7)
      patchLevel4.set_moving_cell(3,5,6)
      return patchLevel4 
   elif selectedLevel==5:
      patchLevel5 = Patch(5,9)
   
      patchLevel5.set_wall(0,1)
      patchLevel5.set_wall(0,2)
      patchLevel5.set_wall(0,3)
      patchLevel5.set_wall(0,4)
      patchLevel5.set_wall(0,5)
      patchLevel5.set_wall(1,0)
      # patchLevel5.set_wall(1,5)
      patchLevel5.set_wall(1,6)
      patchLevel5.set_wall(2,0)
      # patchLevel5.set_wall(2,6)
      patchLevel5.set_wall(2,7)
      patchLevel5.set_wall(2,8)
      patchLevel5.set_wall(0,0)
      patchLevel5.set_wall(3,0)
      
      patchLevel5.set_wall(3,8)
      patchLevel5.set_wall(4,0)
      patchLevel5.set_wall(4,1)
      patchLevel5.set_wall(4,2)
      patchLevel5.set_wall(4,3)
      patchLevel5.set_wall(4,4)
      patchLevel5.set_wall(4,5)
      patchLevel5.set_wall(4,6)
      patchLevel5.set_wall(4,7)
      patchLevel5.set_wall(4,8)
      patchLevel5.set_goal(1,1,2)
      patchLevel5.set_goal(1,5,3)
      
      patchLevel5.set_moving_cell(3,6,7)
      patchLevel5.set_moving_cell(3,5,6)
      return patchLevel5
   elif selectedLevel==6:
      patchLevel6 = Patch(5,9)
   
      patchLevel6.set_wall(0,1)
      patchLevel6.set_wall(0,2)
      patchLevel6.set_wall(0,3)
      patchLevel6.set_wall(0,4)
      patchLevel6.set_wall(0,5)
      patchLevel6.set_wall(1,0)
      # patchLevel6.set_wall(1,5)
      patchLevel6.set_wall(1,6)
      patchLevel6.set_wall(2,0)
      # patchLevel6.set_wall(2,6)
      patchLevel6.set_wall(2,7)
      patchLevel6.set_wall(2,8)
      patchLevel6.set_wall(0,0)
      patchLevel6.set_wall(3,0)
      
      patchLevel6.set_wall(3,8)
      patchLevel6.set_wall(4,0)
      patchLevel6.set_wall(4,1)
      patchLevel6.set_wall(4,2)
      patchLevel6.set_wall(4,3)
      patchLevel6.set_wall(4,4)
      patchLevel6.set_wall(4,5)
      patchLevel6.set_wall(4,6)
      patchLevel6.set_wall(4,7)
      patchLevel6.set_wall(4,8)
      patchLevel6.set_goal(1,1,2)
      patchLevel6.set_goal(1,5,3)
      
      patchLevel6.set_moving_cell(3,6,7)
      patchLevel6.set_moving_cell(3,5,6)
      return patchLevel6
   else:
      print('wronge input, select from 1 ... 6')